### ISSUE TITLE
Retrieve and generation logic in the function level

### ISSUE THREAD

**Issue by pppyb** [microsoft/CodeT#44]
Hi there!

I would like to ask if the retrieve and generation logic for the function part is exactly the same as for the API and line parts(like we just need to add function benchmark?). Is the only difference in evaluation, where unit tests are used instead of EM and ES?

Thanks in advance!

**Comment by zfj1998** [comment]
Unit tests were employed to evaluate the correctness of the completed function body. Sorry we cannot share the source code as stated in the README (We utilize a private library to handle the execution and evaluation of the function-level completion. Due to the license issue, we cannot release the code. ) FYI, here is a repo claiming the reproduction of  RepoEval's function-level dataset, https://github.com/code-rag-bench/code-rag-bench. Hope it helps with your research.

**Comment by pppyb** [comment]
> Unit tests were employed to evaluate the correctness of the completed function body. Sorry we cannot share the source code as stated in the README (We utilize a private library to handle the execution and evaluation of the function-level completion. Due to the license issue, we cannot release the code. ) FYI, here is a repo claiming the reproduction of RepoEval's function-level dataset, https://github.com/code-rag-bench/code-rag-bench. Hope it helps with your research.

Thanks for your reply~ I still want to make sure that the code completion process for function level is the same as api and line level?  cuz I didn't found any function level completion process like function benchmark in code.

Thanks again for your patient reply~

**Comment by zfj1998** [comment]
Thank you for your follow-up question

For function-level code completion, we indeed use a slightly different set of hyperparameters compared to the API and line-level completion processes. Specifically, function-level completion is configured with a window size of 50 lines and a maximum of 500 newly generated tokens per completion, as introduced in the paper.
The core process—iterative retrieval followed by generation—remains consistent with the approach outlined in the paper.
